name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Grant execute permission for compile/gradlew
        working-directory: ./compile
        run: chmod +x gradlew

      - name: Grant execute permission for compile-java-test/gradlew
        working-directory: ./compile-java-test
        run: chmod +x gradlew

      - name: Grant execute permission for compile-kotlin-test/gradlew
        working-directory: ./compile-kotlin-test
        run: chmod +x gradlew

      - name: Grant execute permission for compile-mix-test/gradlew
        working-directory: ./compile-mix-test
        run: chmod +x gradlew

      - name: Build plugin
        working-directory: ./compile
        run: ./gradlew build

      - name: Test plugin against Java
        working-directory: ./compile-java-test
        run: ./gradlew build

      - name: Test plugin against Kotlin
        working-directory: ./compile-kotlin-test
        run: ./gradlew build

      - name: Test plugin against a mix of Java and Kotlin
        working-directory: ./compile-mix-test
        run: ./gradlew build

      - name: Set version
        id: set-version
        working-directory: ./compile
        run: ./gradlew properties | grep "^version:" | awk '{print $2}' | { read v; echo "::set-output name=version::$v"; }

      - name: Print version
        run: echo ${{ steps.set-version.outputs.version }}

      - name: Publish plugin
        if: github.event_name == 'push' && endsWith(steps.set-version.outputs.version, 'SNAPSHOT') == false
        working-directory: ./compile
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
