name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Grant execute permission for compile/gradlew
        working-directory: ./compile
        run: chmod +x gradlew

      - name: Build compile-plugin
        working-directory: ./compile
        run: ./gradlew build

      - name: Test
        run: ./gradlew build

      - name: Set version
        id: set-version
        run: ./gradlew properties | grep "^version:" | awk '{print $2}' | { read v; echo "version=$v" >> $GITHUB_OUTPUT; }

      - name: Print version
        run: echo ${{ steps.set-version.outputs.version }}

      - name: Publish plugin
        working-directory: ./compile
        if: github.event_name == 'push' && endsWith(steps.set-version.outputs.version, 'SNAPSHOT') == false
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
